### PR TITLE
Added Linked lists and changed the structure of C_implem

### PR DESCRIPTION
**Pull request by Drakzia**
- ### Added a basic implementation of linked lists that will be useful for other algoritms/structures
Building the project results in an executable wich prints a list of integers from 1 to 100

- ### Cleared the structure of C_implem
Running make in the directory runs make in all subfolders (exept build). Projects should build inside a dedicated folder inside the build folder. The content of the build folder is ignored.

### CODE REVIEW

**Comment by imartayan** [comment]
I think you should add a `free` inside the `pop_int_list` function.

**Comment by anima-libera** [comment]
`append_...` should not be named this way, as "append" means "add at the end", 
a free is missing from the pop function,
and a function to free a list and all its content should be provided to avoid memory leaks

**Review by anima-libera — CHANGES_REQUESTED** [review]
See comments uwu

**Review by anima-libera — APPROVED** [review]

**Review by acorrenson — COMMENTED** [review]
You should add a "size" field and implement the function "length" (in O(1))

**Comment by Drakzia** [comment]
> 
> 
> You should add a "size" field and implement the function "length" (in O(1))

done

**Review by acorrenson — APPROVED** [review]
Everything seems ok

**Pull request merged**
