### PR TITLE
Implemented binary heap with vec backend

### PR DESCRIPTION
**Pull request by Moxinilian**
Recursive type coming right after!
This one should be easier to review!

### CODE REVIEW

**Comment by Moxinilian** [comment]
I fucked up, please wait for me to fix it before reviewing.

**Review by acorrenson — APPROVED** [review]
Function names may be more explicit

**Comment by Moxinilian** [comment]
Any suggestion? I struggled for a while to end up picking "fix".

**Comment by acorrenson** [comment]
Honestly idk. Maybe heapify_up and heapify_down. Or move up move down.
These are the function names suggested in many implementations (cf C. Filliâtre and its Ocaml module implementing bheaps )

**Comment by Moxinilian** [comment]
Heapify is great, commit incoming.

**Review by anima-libera — APPROVED** [review]

**Pull request merged**
